name: Setup Go environment - with specific cache key
description: Install go and add it to the PATH
author: 'hermanbanken'

inputs:
  key: # id of input
    description: 'How to identify the cache unique per step; example "job:lint:go"'
    required: true
  go-version:
    description: which Go version to use; fixed
    default: ""
  go-version-file:
    description: which Go version to use; read from go.mod file
    default: "go.mod"
  token:
    description: Used to pull node distributions from go-versions. Since there's a default, this is typically not supplied by the user. When running this action on github.com, the default value is sufficient. When running on GHES, you can pass a personal access token for github.com if you are experiencing rate limiting.
    default: ${{ github.server_url == 'https://github.com' && github.token || '' }}
  architecture:
    description: 'Target architecture for Go to use. Examples: x86, x64. Will use system architecture by default.'

runs:
  using: "composite"
  steps:
    - name: Cache go
      uses: actions/cache@v3
      with:
        key: ${{ inputs.key }}
        path: | # what setup-go caches too (runs `go env GOMODCACHE` and `go env GOCACHE` to compute this, but it is static)
          /home/runner/go/pkg/mod
          /home/runner/.cache/go-build
    - name: Setup go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ inputs.go-version }}
        go-version-file: ${{ inputs.go-version-file }}
        token: ${{ inputs.token }}
        architecture: ${{ inputs.architecture }}
        cache: false
